// console.log("hello world");
//  document.write('hello world');
 var num= 10;
 console.log(num);
 console.log(typeof(num));
 num = false;
 console.log(num);
 console.log(typeof(num));
 num ="Sanjeev";
 console.log(num);
 console.log(typeof(num));
 num = null;
 console.log(num);
 console.log(typeof(num));
 num = undefined;
 console.log(num);
 console.log(typeof(num)); 